# Preceptron step by step

importing Numpy for matrix math

In [16]:
import numpy as np

Defining sigmoid function

In [17]:
def sigmoid(x):
        return 1/(1 + np.exp(-x))

defining identity function

In [34]:
def identity(x):
    return x

input values

In [11]:
x = np.array([7.0, 2.0])

weight 1

In [12]:
w1 = np.array([[0.7, 0.9, 0.3],[0.5,0.4,0.1]])

bias 1

In [13]:
b1 = np.array([1, 1, 1])

using dot product

In [18]:
a1 = np.dot(x, w1) + b1

In [19]:
a1

array([6.9, 8.1, 3.3])

implimenting the sigmoid function

In [20]:
z1 = sigmoid(a1)

In [21]:
z1

array([0.99899323, 0.99969655, 0.96442881])

Weight 2

In [22]:
w2 = np.array([[0.2, 0.3],[0.4, 0.5],[0.22, 0.1234]])

bias 2

In [23]:
b2 = np.array([0.5, 0.5])

dot product plus bias

In [24]:
a2 = np.dot(z1, w2) + b2

using sigmoid function

In [25]:
z2 = sigmoid(a2)

weight 3

In [26]:
w3 = np.array([[0.7, 0.1],[0.123 , 0.314]])

bias 3

In [27]:
b3 = np.array([0.1, 0.2])

dot product plus bias

In [30]:
a3 = np.dot(z2, w3) + b3

In [32]:
a3

array([0.75050477, 0.53158747])

using identity function

In [36]:
z3 = identity(a3)

preceptron outputs

In [37]:
z3

array([0.75050477, 0.53158747])

# compared to the multilayer_preceptron.py

multilayer_preceptron.py

In [42]:
class MultiLayerPreceptron:
    def __init__(self):
        self.net = ()
        pass

    def init_network(self):
        net = {}
        # first layer from class
        net['w1'] = np.array([[0.7, 0.9, 0.3],[0.5,0.4,0.1]])
        net['b1'] = np.array([1, 1, 1])
        # second layer from class
        net['w2'] = np.array([[0.2, 0.3],[0.4, 0.5],[0.22, 0.1234]])
        net['b2'] = np.array([0.5, 0.5])    
        # third layer to output
        net['w3'] = np.array([[0.7, 0.1],[0.123 , 0.314]])
        net['b3'] = np.array([0.1, 0.2])

        self.net = net
        
    def sigmoid(self,x):
        return 1/(1 + np.exp(-x))

    def identity(self, x):
        return x

    def forward(self,x):
        w1, w2, w3 = self.net['w1'], self.net['w2'], self.net['w3']
        b1, b2, b3 = self.net['b1'], self.net['b2'], self.net['b3']

        a1 = np.dot(x, w1) + b1
        z1 = self.sigmoid(a1)

        a2 = np.dot(z1, w2) + b2
        z2 = self.sigmoid(a2)

        a3 = np.dot(z2, w3) + b3
        y = self.identity(a3)

        return y

testing same inputs

In [43]:
MLP = MultiLayerPreceptron()
MLP.init_network()
y = MLP.forward(np.array([7.0, 2.0]))

In [44]:
y

array([0.75050477, 0.53158747])

# both results are the same, multilayer preceptron is working